import { Car, Dealer } from './types';

export const mockDealers: Dealer[] = [
  {
    id: 'd1',
    name: 'Apex Automotive Group',
    location: 'Munich, Germany',
    rating: 4.9,
    verified: true,
    phone: '+49 89 2345 6789',
    email: 'info@apex-motors.de',
    logoUrl: 'https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?w=100&auto=format&fit=crop&q=80',
    certifiedBrands: ['Porsche', 'BMW', 'Mercedes-Benz', 'Audi'],
    listingsCount: 48,
  },
  {
    id: 'd2',
    name: 'Stuttgart Performance Center',
    location: 'Stuttgart, Germany',
    rating: 4.8,
    verified: true,
    phone: '+49 711 9876 5432',
    email: 'sales@stuttgart-performance.de',
    logoUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=100&auto=format&fit=crop&q=80',
    certifiedBrands: ['Porsche', 'Aston Martin', 'Ferrari'],
    listingsCount: 32,
  },
  {
    id: 'd3',
    name: 'Horizon Electric Vehicles',
    location: 'San Jose, CA, USA',
    rating: 4.9,
    verified: true,
    phone: '+1 (408) 555-0199',
    email: 'listings@horizonev.com',
    logoUrl: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=100&auto=format&fit=crop&q=80',
    certifiedBrands: ['Tesla', 'Porsche', 'Rivian'],
    listingsCount: 20,
  },
  {
    id: 'd4',
    name: 'Nippon GT Heritage',
    location: 'Tokyo, Japan',
    rating: 4.7,
    verified: true,
    phone: '+81 3 5555 1234',
    email: 'support@nippongt.jp',
    logoUrl: 'https://images.unsplash.com/photo-1616422285623-13ff0162193c?w=100&auto=format&fit=crop&q=80',
    certifiedBrands: ['Nissan', 'Toyota', 'Honda'],
    listingsCount: 15,
  },
];

export const mockCars: Car[] = [
  {
    id: 'c1',
    brand: 'Porsche',
    model: '911 GT3 RS',
    year: 2025,
    price: 223000,
    mileage: 120,
    fuelType: 'Petrol',
    transmission: 'Dual-Clutch',
    country: 'Germany',
    category: 'Supercar',
    heroImage: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800&auto=format&fit=crop&q=80',
    imageGallery: [
      'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1611245801725-27a4d21b2ee3?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop&q=80',
    ],
    specifications: {
      engine: '4.0L Naturally Aspirated Boxer 6',
      power: '518 hp @ 8,500 rpm',
      torque: '343 lb-ft @ 6,300 rpm',
      acceleration: '3.0s (0-60 mph)',
      topSpeed: '184 mph',
      weight: '3,268 lbs',
      driveTrain: 'RWD',
    },
    colors: [
      { name: 'Python Green', hex: '#10b981', glowHex: '#34d399' },
      { name: 'Guards Red', hex: '#ef4444', glowHex: '#f87171' },
      { name: 'GT Silver Metallic', hex: '#9ca3af', glowHex: '#e5e7eb' },
      { name: 'Shark Blue', hex: '#3b82f6', glowHex: '#60a5fa' },
    ],
    features: [
      'DRS (Drag Reduction System)',
      'Weissach Package Lightweight Carbon Components',
      'Adjustable Aero Wing (Aero-Vector Control)',
      'Carbon Ceramic Brakes (PCCB)',
      'Porsche Active Suspension Management (PASM)',
      'Monolithic Race Wheels with Center Locks',
    ],
    dealerId: 'd1',
    rating: 4.9,
    reviewsCount: 24,
    reviews: [
      {
        id: 'r1',
        author: 'Sebastian V.',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
        rating: 5,
        date: '2026-04-12',
        comment: 'The handling on the Nürburgring is completely out of this world. There is nothing else like it that communicates so purely.',
        verifiedBuyer: true,
      },
      {
        id: 'r2',
        author: 'Alex Carter',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
        rating: 4.8,
        date: '2026-05-01',
        comment: 'A true track animal. It screams all the way to 9,000 RPM. A bit stiff for groceries, but you do not buy an RS for groceries.',
        verifiedBuyer: true,
      },
    ],
    accentColor: 'emerald',
    isNewArrival: true,
    isPopular: true,
  },
  {
    id: 'c2',
    brand: 'Tesla',
    model: 'Roadster',
    year: 2026,
    price: 200000,
    mileage: 5,
    fuelType: 'Electric',
    transmission: 'Automatic',
    country: 'USA',
    category: 'Hypercar',
    heroImage: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&auto=format&fit=crop&q=80',
    imageGallery: [
      'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&auto=format&fit=crop&q=80',
    ],
    specifications: {
      engine: 'Tri-Motor Plaid AWD Propulsion',
      power: '1,240 hp (Equivalent)',
      torque: '10,000 Nm wheel torque',
      acceleration: '1.9s (0-60 mph)',
      topSpeed: '250+ mph',
      weight: '4,400 lbs',
      batteryRange: '620 miles',
      driveTrain: 'AWD',
    },
    colors: [
      { name: 'Solid Red', hex: '#dc2626', glowHex: '#f87171' },
      { name: 'Ultra Black', hex: '#111827', glowHex: '#4b5563' },
      { name: 'Pearl White Multi-Coat', hex: '#f9fafb', glowHex: '#ffffff' },
    ],
    features: [
      'SpaceX Cold Gas Thrusters Prep Pack',
      'Removable Lightweight Glass Roof',
      'Full Self-Driving Computer V5',
      'Torque Vectoring Tri-Motor Propulsion',
      'Fighter-Jet Inspired Yoke Steering',
    ],
    dealerId: 'd3',
    rating: 5.0,
    reviewsCount: 8,
    reviews: [
      {
        id: 'r3',
        author: 'Elon M.',
        avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&auto=format&fit=crop&q=80',
        rating: 5,
        date: '2026-03-20',
        comment: 'You will feel like you are taking off into low Earth orbit. Best handling electric sports machine ever built.',
        verifiedBuyer: false,
      },
    ],
    accentColor: 'cyan',
    isNewArrival: true,
  },
  {
    id: 'c3',
    brand: 'Lamborghini',
    model: 'Revuelto',
    year: 2025,
    price: 608000,
    mileage: 45,
    fuelType: 'Hybrid',
    transmission: 'Dual-Clutch',
    country: 'Italy',
    category: 'Hypercar',
    heroImage: 'https://images.unsplash.com/photo-1621135802920-133df287f89c?w=800&auto=format&fit=crop&q=80',
    imageGallery: [
      'https://images.unsplash.com/photo-1621135802920-133df287f89c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&auto=format&fit=crop&q=80',
    ],
    specifications: {
      engine: '6.5L Naturally Aspirated V12 + 3 Electric Motors',
      power: '1,001 hp Combined',
      torque: '595 lb-ft @ 6,750 rpm',
      acceleration: '2.5s (0-60 mph)',
      topSpeed: '217 mph',
      weight: '3,950 lbs',
      batteryRange: '6 miles (EV Only)',
      driveTrain: 'AWD',
    },
    colors: [
      { name: 'Arancio Apodis (Orange)', hex: '#f97316', glowHex: '#fb923c' },
      { name: 'Giallo Auge (Yellow)', hex: '#eab308', glowHex: '#facc15' },
      { name: 'Verde Turbine (Matte Green)', hex: '#3f6212', glowHex: '#a3e635' },
    ],
    features: [
      'Monofuselage Fully Carbon Chassis',
      'Lamborghini Dinamica Veicolo Integrata (LDVI)',
      'Hydraulics Front Axle Lift Engine',
      'Triple Engine Custom Hybrid Torque Fill',
      'Y-style Signature Headlamps with LED Matrix',
    ],
    dealerId: 'd2',
    rating: 4.9,
    reviewsCount: 15,
    reviews: [
      {
        id: 'r4',
        author: 'Marco Rossi',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
        rating: 5,
        date: '2026-01-15',
        comment: 'V12 hybrid is pure art. Silent on exit from my driveway, then pure glorious V12 orchestra on the main road.',
        verifiedBuyer: true,
      },
    ],
    accentColor: 'orange',
    isPopular: true,
  },
  {
    id: 'c4',
    brand: 'Ferrari',
    model: 'SF90 Stradale',
    year: 2024,
    price: 524000,
    mileage: 650,
    fuelType: 'Hybrid',
    transmission: 'Dual-Clutch',
    country: 'Italy',
    category: 'Supercar',
    heroImage: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&auto=format&fit=crop&q=80',
    imageGallery: [
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1592853625527-411bd7987311?w=800&auto=format&fit=crop&q=80',
    ],
    specifications: {
      engine: '4.0L Twin-Turbo V8 + 3 Electric Motors',
      power: '986 hp Combined',
      torque: '590 lb-ft @ 6,000 rpm',
      acceleration: '2.5s (0-60 mph)',
      topSpeed: '211 mph',
      weight: '3,461 lbs',
      batteryRange: '15 miles (EV Only)',
      driveTrain: 'AWD',
    },
    colors: [
      { name: 'Rosso Corsa (Ferrari Red)', hex: '#be123c', glowHex: '#f43f5e' },
      { name: 'Nero Daytona (Black Metallic)', hex: '#030712', glowHex: '#6b7280' },
      { name: 'Giallo Modena (Yellow)', hex: '#fbbf24', glowHex: '#fef08a' },
    ],
    features: [
      'eManettino Driving Controls with Qualify Mode',
      'Assetto Fiorano Track Package',
      'Dual Front Motor Torque Vectoring (RAC-e)',
      'Carbon Fiber Aero Diffusers',
    ],
    dealerId: 'd2',
    rating: 4.8,
    reviewsCount: 11,
    reviews: [
      {
        id: 'r5',
        author: 'Lando N.',
        avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop&q=80',
        rating: 5,
        date: '2025-11-09',
        comment: 'Qualify mode turns this space-age machine into a pure rocket ship. Best-in-class handling and acceleration.',
        verifiedBuyer: true,
      },
    ],
    accentColor: 'rose',
  },
  {
    id: 'c5',
    brand: 'Porsche',
    model: 'Taycan Turbo GT',
    year: 2025,
    price: 230000,
    mileage: 15,
    fuelType: 'Electric',
    transmission: 'Automatic',
    country: 'Germany',
    category: 'Sedan',
    heroImage: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800&auto=format&fit=crop&q=80',
    imageGallery: [
      'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800&auto=format&fit=crop&q=80',
    ],
    specifications: {
      engine: 'Dual Motor Performance Electric EV',
      power: '1,019 hp in Attack Mode',
      torque: '914 lb-ft',
      acceleration: '2.1s (0-60 mph)',
      topSpeed: '180 mph',
      weight: '4,850 lbs',
      batteryRange: '340 miles',
      driveTrain: 'AWD',
    },
    colors: [
      { name: 'Pale Blue Metallic', hex: '#bfdbfe', glowHex: '#60a5fa' },
      { name: 'Purple Metallic', hex: '#a855f7', glowHex: '#c084fc' },
      { name: 'Satin Carbon', hex: '#374151', glowHex: '#9ca3af' },
    ],
    features: [
      'Porsche Active Ride System',
      'Attack Mode Formula E Style Power Boost (10-sec)',
      'Lightweight Carbon Fiber Trim interior',
      'Ceramic Composite Brake Calipers in Victory Gold',
    ],
    dealerId: 'd1',
    rating: 4.9,
    reviewsCount: 6,
    reviews: [],
    accentColor: 'purple',
    isNewArrival: true,
  },
  {
    id: 'c6',
    brand: 'Tesla',
    model: 'Model S Plaid',
    year: 2024,
    price: 89990,
    mileage: 1800,
    fuelType: 'Electric',
    transmission: 'Automatic',
    country: 'USA',
    category: 'Sedan',
    heroImage: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&auto=format&fit=crop&q=80',
    imageGallery: [
      'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&auto=format&fit=crop&q=80',
    ],
    specifications: {
      engine: 'Tri-Motor Plaid AWD Propulsion',
      power: '1,020 hp',
      torque: '1,050 lb-ft',
      acceleration: '1.99s (0-60 mph)',
      topSpeed: '200 mph',
      weight: '4,766 lbs',
      batteryRange: '396 miles',
      driveTrain: 'AWD',
    },
    colors: [
      { name: 'Midnight Gray Metallic', hex: '#4b5563', glowHex: '#9ca3af' },
      { name: 'Solid Black', hex: '#0f172a', glowHex: '#475569' },
      { name: 'Deep Blue Metallic', hex: '#1e3a8a', glowHex: '#3b82f6' },
    ],
    features: [
      'Autopilot Comfort Suite',
      'Acoustic Multi-Layer Privacy Glass',
      'Yaw Action Active Torque Vectoring',
      'Ultra High-Fidelity 22-Speaker Audio System',
      'Fold-out Gaming Screen Interior Console',
    ],
    dealerId: 'd3',
    rating: 4.7,
    reviewsCount: 38,
    reviews: [],
    accentColor: 'blue',
  },
  {
    id: 'c7',
    brand: 'Porsche',
    model: 'Cayenne E-Hybrid',
    year: 2025,
    price: 146000,
    mileage: 24,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    country: 'Germany',
    category: 'SUV',
    heroImage: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop&q=80',
    imageGallery: [
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop&q=80',
    ],
    specifications: {
      engine: '4.0L Twin-Turbo V8 + Electric Hub Motor',
      power: '729 hp Combined',
      torque: '700 lb-ft',
      acceleration: '3.5s (0-60 mph)',
      topSpeed: '183 mph',
      weight: '5,500 lbs',
      batteryRange: '48 miles (EV-only)',
      driveTrain: 'AWD',
    },
    colors: [
      { name: 'Chromite Black Metallic', hex: '#111827', glowHex: '#4b5563' },
      { name: 'Carrara White Metallic', hex: '#f3f4f6', glowHex: '#ffffff' },
      { name: 'Montego Blue Metallic', hex: '#1d4ed8', glowHex: '#60a5fa' },
    ],
    features: [
      'Luxury Premium Active Air Suspension',
      'Adaptive Cruise Control with Lane Keep',
      'Porsche Dynamic Light System Plus (PDLS+)',
      '14-way Electric Comfort Massaging Seats',
    ],
    dealerId: 'd1',
    rating: 4.8,
    reviewsCount: 9,
    reviews: [],
    accentColor: 'teal',
  },
  {
    id: 'c8',
    brand: 'Nissan',
    model: 'GT-R Nismo',
    year: 2024,
    price: 221000,
    mileage: 430,
    fuelType: 'Petrol',
    transmission: 'Dual-Clutch',
    country: 'Japan',
    category: 'Supercar',
    heroImage: 'https://images.unsplash.com/photo-1532581291347-9c39cf10a73c?w=800&auto=format&fit=crop&q=80',
    imageGallery: [
      'https://images.unsplash.com/photo-1532581291347-9c39cf10a73c?w=800&auto=format&fit=crop&q=80',
    ],
    specifications: {
      engine: '3.8L Twin-Turbofully Custom V6',
      power: '600 hp @ 6,800 rpm',
      torque: '481 lb-ft @ 3,600 rpm',
      acceleration: '2.7s (0-60 mph)',
      topSpeed: '196 mph',
      weight: '3,810 lbs',
      driveTrain: 'AWD',
    },
    colors: [
      { name: 'Nismo Stealth Gray', hex: '#6b7280', glowHex: '#9ca3af' },
      { name: 'Super Silver Quad Coat', hex: '#d1d5db', glowHex: '#f3f4f6' },
      { name: 'Solid Pearl Black', hex: '#111827', glowHex: '#374151' },
    ],
    features: [
      'Carbon-Fiber Nismo Hood and Roof Panels',
      'Titanium Custom Racing Exhaust Pipes',
      'Bilstein DampTronic Active Suspension dampers',
      'RAYS 20-inch Forged Aluminum Rims',
    ],
    dealerId: 'd4',
    rating: 4.8,
    reviewsCount: 19,
    reviews: [],
    accentColor: 'indigo',
  },
  {
    id: 'c9',
    brand: 'BMW',
    model: 'i7 M70 xDrive',
    year: 2025,
    price: 168000,
    mileage: 10,
    fuelType: 'Electric',
    transmission: 'Automatic',
    country: 'Germany',
    category: 'Sedan',
    heroImage: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&auto=format&fit=crop&q=80',
    imageGallery: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&auto=format&fit=crop&q=80',
    ],
    specifications: {
      engine: 'Dual Motor Performance Electric EV',
      power: '650 hp',
      torque: '811 lb-ft',
      acceleration: '3.5s (0-60 mph)',
      topSpeed: '155 mph',
      weight: '5,920 lbs',
      batteryRange: '295 miles',
      driveTrain: 'AWD',
    },
    colors: [
      { name: 'Two-Tone Oxide Grey/Sapphire', hex: '#4b5563', glowHex: '#9ca3af' },
      { name: 'Frozen Deep Black matte', hex: '#1f2937', glowHex: '#4b5563' },
      { name: 'Liquid Bronze Metallic', hex: '#d97706', glowHex: '#fbbf24' },
    ],
    features: [
      'BMW 31.3-inch Ultra-Theater Screen for Rear Cabin',
      'Bowers & Wilkins 4D Holographic Diamond Audio',
      'Dynamic Crystal LED Adaptive Icon Headlamps',
      'Panoramic Sky Lounge LED Roof Panels',
    ],
    dealerId: 'd1',
    rating: 4.9,
    reviewsCount: 14,
    reviews: [],
    accentColor: 'amber',
    isPopular: true,
  },
  {
    id: 'c10',
    brand: 'Toyota',
    model: 'GR Supra M/T',
    year: 2024,
    price: 58000,
    mileage: 3200,
    fuelType: 'Petrol',
    transmission: 'Manual',
    country: 'Japan',
    category: 'Coupe',
    heroImage: 'https://images.unsplash.com/photo-1616422285623-13ff0162193c?w=800&auto=format&fit=crop&q=80',
    imageGallery: [
      'https://images.unsplash.com/photo-1616422285623-13ff0162193c?w=800&auto=format&fit=crop&q=80',
    ],
    specifications: {
      engine: '3.0L twin-scroll Turbocharged Inline-6',
      power: '382 hp @ 5,800 rpm',
      torque: '368 lb-ft @ 1,800 rpm',
      acceleration: '4.2s (0-60 mph)',
      topSpeed: '155 mph',
      weight: '3,400 lbs',
      driveTrain: 'RWD',
    },
    colors: [
      { name: 'Mikan Blast (Premium Orange)', hex: '#f97316', glowHex: '#fb923c' },
      { name: 'Absolute Zero White', hex: '#ffffff', glowHex: '#e5e7eb' },
      { name: 'Nocturnal Black', hex: '#111827', glowHex: '#4b5563' },
    ],
    features: [
      '6-Speed Intelligence Manual Gearbox (iMT)',
      'Active Electronic Sport Rear Differential',
      'Adaptive Variable Sports Suspension',
      'Brembo 4-piston Front Brake Aluminum Calipers',
    ],
    dealerId: 'd4',
    rating: 4.6,
    reviewsCount: 42,
    reviews: [],
    accentColor: 'orange',
  },
];
